let listings=[];let userLocation=null;let currentArea="all";let activePhotos=[];let activePhotoIndex=0;
const listingsEl=document.getElementById("listings"),statusEl=document.getElementById("status"),useLocationBtn=document.getElementById("useLocationBtn"),areaFilter=document.getElementById("areaFilter"),lightbox=document.getElementById("lightbox"),lightboxImage=document.getElementById("lightboxImage"),closeLightbox=document.getElementById("closeLightbox"),prevPhoto=document.getElementById("prevPhoto"),nextPhoto=document.getElementById("nextPhoto"),lightboxThumbs=document.getElementById("lightboxThumbs");init();
async function init(){try{const response=await fetch("listings.json?v="+Date.now());if(!response.ok)throw new Error("Unable to fetch listings.json");listings=await response.json();populateAreaFilter();renderListings()}catch(error){console.error(error);listingsEl.innerHTML="<p class='empty'>Unable to load listings. Please check that listings.json is valid JSON.</p>"}}
function populateAreaFilter(){const areas=[...new Set(listings.map(item=>item.area).filter(Boolean))].sort();areas.forEach(area=>{const option=document.createElement("option");option.value=area;option.textContent=area;areaFilter.appendChild(option)})}
useLocationBtn.addEventListener("click",()=>{if(!navigator.geolocation){statusEl.textContent="GPS location is not supported by this browser.";return}statusEl.textContent="Requesting location permission...";navigator.geolocation.getCurrentPosition(position=>{userLocation={latitude:position.coords.latitude,longitude:position.coords.longitude};statusEl.textContent="Listings are now sorted by nearest distance.";renderListings()},()=>{statusEl.textContent="Location permission was not allowed. Showing default order."},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})});
areaFilter.addEventListener("change",event=>{currentArea=event.target.value;renderListings()});
function renderListings(){let visibleListings=listings.filter(item=>currentArea==="all"||item.area===currentArea);visibleListings=visibleListings.map(item=>({...item,distanceKm:userLocation?calculateDistanceKm(userLocation.latitude,userLocation.longitude,item.latitude,item.longitude):null}));visibleListings.sort((a,b)=>{if(userLocation)return a.distanceKm-b.distanceKm;if(a.featured!==b.featured)return a.featured?-1:1;return a.name.localeCompare(b.name)});if(!visibleListings.length){listingsEl.innerHTML="<p class='empty'>No listings found for this area.</p>";return}listingsEl.innerHTML=visibleListings.map((item,index)=>createListingCard(item,index)).join("");attachThumbnailEvents(visibleListings)}
function createListingCard(item,index){const allPhotos=Array.isArray(item.photos)?item.photos:[],firstThree=allPhotos.slice(0,3),extraCount=Math.max(0,allPhotos.length-3),distanceText=item.distanceKm!==null?`${item.distanceKm.toFixed(1)} km away`:"",mapsUrl=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(item.address)}`,whatsappMessage=encodeURIComponent(`Hi ${item.name}, I found your listing on NearByMassage. May I check your availability?`),whatsappUrl=item.whatsapp?`https://wa.me/${item.whatsapp}?text=${whatsappMessage}`:"",callUrl=item.phone?`tel:${item.phone}`:"#";const thumbs=firstThree.map((photo,photoIndex)=>`<button class="thumb-wrap" data-listing-index="${index}" data-photo-index="${photoIndex}" aria-label="Open ${escapeHtml(item.name)} photo ${photoIndex+1}"><img class="thumb" loading="lazy" src="${escapeHtml(photo)}" alt="${escapeHtml(item.name)} thumbnail ${photoIndex+1}" onerror="this.src='placeholder.svg'" />${photoIndex===2&&extraCount>0?`<span class="more-count">+${extraCount}</span>`:""}</button>`).join("");return `<article class="card"><div class="thumb-grid">${thumbs}</div><div class="card-main"><div class="top-line">${item.featured?"<span class='badge'>☆ Featured</span>":""}</div><h3>${escapeHtml(item.name)}</h3><p class="area">${escapeHtml(item.area||"")}</p><p class="meta">${escapeHtml(item.address||"")}</p><p class="desc">${escapeHtml(item.description||"")}</p></div><div class="card-side">${distanceText?`<p class="distance">${distanceText}</p>`:""}<a class="action-btn primary" href="${callUrl}">☎ Call</a>${whatsappUrl?`<a class="action-btn" href="${whatsappUrl}" target="_blank" rel="noopener">☘ WhatsApp</a>`:""}<a class="action-btn map" href="${mapsUrl}" target="_blank" rel="noopener">📍 Show on Map</a></div>${item.page ? `
<a class="action-btn details"
   href="${item.page}">
   📄 View Details
</a>` : ""}</article>`}
function attachThumbnailEvents(visibleListings){document.querySelectorAll(".thumb-wrap").forEach(button=>{button.addEventListener("click",()=>{const listingIndex=Number(button.dataset.listingIndex),photoIndex=Number(button.dataset.photoIndex);openLightbox(visibleListings[listingIndex].photos||[],photoIndex)})})}
function openLightbox(photos,index){activePhotos=photos;activePhotoIndex=index;updateLightbox();lightbox.hidden=false}
function updateLightbox(){if(!activePhotos.length)return;lightboxImage.src=activePhotos[activePhotoIndex];lightboxThumbs.innerHTML=activePhotos.map((photo,index)=>`<img class="lightbox-thumb ${index===activePhotoIndex?"active":""}" src="${escapeHtml(photo)}" alt="Thumbnail ${index+1}" data-index="${index}" onerror="this.src='placeholder.svg'" />`).join("");document.querySelectorAll(".lightbox-thumb").forEach(thumb=>{thumb.addEventListener("click",()=>{activePhotoIndex=Number(thumb.dataset.index);updateLightbox()})})}
function showPreviousPhoto(){if(!activePhotos.length)return;activePhotoIndex=(activePhotoIndex-1+activePhotos.length)%activePhotos.length;updateLightbox()}function showNextPhoto(){if(!activePhotos.length)return;activePhotoIndex=(activePhotoIndex+1)%activePhotos.length;updateLightbox()}
closeLightbox.addEventListener("click",()=>lightbox.hidden=true);prevPhoto.addEventListener("click",showPreviousPhoto);nextPhoto.addEventListener("click",showNextPhoto);lightbox.addEventListener("click",event=>{if(event.target===lightbox)lightbox.hidden=true});document.addEventListener("keydown",event=>{if(lightbox.hidden)return;if(event.key==="Escape")lightbox.hidden=true;if(event.key==="ArrowLeft")showPreviousPhoto();if(event.key==="ArrowRight")showNextPhoto()});
function calculateDistanceKm(lat1,lon1,lat2,lon2){const earthRadiusKm=6371,dLat=toRadians(lat2-lat1),dLon=toRadians(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(toRadians(lat1))*Math.cos(toRadians(lat2))*Math.sin(dLon/2)**2;return earthRadiusKm*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}function toRadians(degrees){return degrees*Math.PI/180}function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
